# Generated by Django 3.2.9 on 2021-12-13 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='qty',
        ),
    ]
