# Generated by Django 3.2.9 on 2021-12-27 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cars', models.CharField(max_length=100, verbose_name='Марка автомобиля')),
                ('model', models.CharField(max_length=100, verbose_name='Модель автомобиля')),
                ('vin', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('number', models.CharField(blank=True, max_length=9, null=True, unique=True, verbose_name='Номер автомобиля')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Гараж',
                'verbose_name_plural': 'Гаражи',
            },
        ),
    ]
