# Generated by Django 3.2.9 on 2021-12-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_car_carsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='year',
            field=models.CharField(default=1, max_length=4, verbose_name='Год выпуска'),
            preserve_default=False,
        ),
    ]
