# Generated by Django 3.2.9 on 2021-12-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_garage_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garage',
            name='number',
            field=models.CharField(blank=True, default=None, max_length=9, null=True, unique=True, verbose_name='Номер автомобиля'),
        ),
    ]
