# Generated by Django 3.2.9 on 2021-12-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_garage_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garage',
            name='number',
            field=models.CharField(blank=True, default=None, max_length=9, unique=True, verbose_name='Номер автомобиля'),
        ),
    ]
