# Generated by Django 3.2.9 on 2021-12-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_garage_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garage',
            name='vin',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
