# Generated by Django 3.2.9 on 2021-12-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активность')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('edit_date', models.DateField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=30, verbose_name='Название слайдера')),
                ('image', models.ImageField(upload_to='slider_image/')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('sub_title', models.CharField(max_length=50, verbose_name='Подзаголовок')),
                ('button', models.CharField(max_length=30, verbose_name='Текст кнопки')),
                ('button_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Путь кнопки')),
                ('button_active', models.BooleanField(default=False, verbose_name='Вывести кнопку')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдер',
                'ordering': ['created_date'],
            },
        ),
    ]
